use crate::agents::agent::{Agent, Task, TaskType, TaskPriority, AgentResult, ExecutionContext};
use crate::agents::agent_factory::AgentFactory;
use crate::agents::agent_config::AgentConfig;
use crate::agents::visibility::{VisibilityManager, ExecutionPhase, VerbosityLevel};
use anyhow::Result;
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use tokio::sync::RwLock;
use colored::Colorize;

/// Planning Coordinator - manages task decomposition and agent dispatch
pub struct PlanningCoordinator {
    agent_factory: Arc<AgentFactory>,
    agent_configs: HashMap<String, AgentConfig>,
    task_queue: Arc<RwLock<VecDeque<Task>>>,
    active_agents: Arc<RwLock<HashMap<String, AgentHandle>>>,
    conversation_state: Arc<RwLock<Vec<crate::agents::agent::ChatMessage>>>,
    visibility_manager: Arc<RwLock<VisibilityManager>>,
}

#[derive(Debug, Clone)]
struct AgentHandle {
    name: String,
    task_id: String,
    start_time: std::time::Instant,
}

impl PlanningCoordinator {
    pub fn new(agent_factory: Arc<AgentFactory>) -> Self {
        let session_id = format!("session_{}", chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0));
        let visibility_manager = Arc::new(RwLock::new(VisibilityManager::new(session_id)));
        
        Self {
            agent_factory,
            agent_configs: HashMap::new(),
            task_queue: Arc::new(RwLock::new(VecDeque::new())),
            active_agents: Arc::new(RwLock::new(HashMap::new())),
            conversation_state: Arc::new(RwLock::new(Vec::new())),
            visibility_manager,
        }
    }

    /// Set verbosity level for visibility manager
    pub async fn set_verbosity_level(&self, level: VerbosityLevel) {
        let mut visibility = self.visibility_manager.write().await;
        visibility.set_verbosity_level(level);
    }

    /// Load agent configurations from directory
    pub async fn load_agent_configs(&mut self, config_dir: &std::path::Path) -> Result<()> {
        let mut entries = tokio::fs::read_dir(config_dir).await?;

        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("json") {
                let content = tokio::fs::read_to_string(&path).await?;
                let config: AgentConfig = serde_json::from_str(&content)?;

                // Validate configuration
                config.validate()
                    .map_err(|e| anyhow::anyhow!("Invalid config in {}: {}", path.display(), e))?;

                self.agent_configs.insert(config.name.clone(), config);
                println!("{} Loaded agent configuration: {}", "📋".blue(), path.display());
            }
        }

        Ok(())
    }

    /// Process a user request and coordinate agent execution
    pub async fn process_user_request(&mut self, request: &str, context: &ExecutionContext) -> Result<AgentResult> {
        println!("{} Processing request: {}", "🤔".yellow(), request);

        // Update visibility manager with planning phase
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.set_phase(ExecutionPhase::Planning);
        }

        // 1. Analyze request and create initial task
        let initial_task = self.analyze_request(request).await?;

        // 2. Decompose task if needed
        let tasks = self.decompose_task(initial_task).await?;
        let total_tasks = tasks.len();

        // Update visibility manager with task count
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.set_phase(ExecutionPhase::TaskExecution);
            // Register all tasks with visibility manager
            for task in &tasks {
                visibility.register_task(task.id.clone(), task.description.clone());
            }
        }

        // 3. Add tasks to queue
        {
            let mut queue = self.task_queue.write().await;
            for task in tasks {
                queue.push_back(task);
            }
        }

        // 4. Execute all tasks
        let mut results = Vec::new();
        let mut completed_count = 0;
        
        while !self.task_queue.read().await.is_empty() {
            // Update status line before each task
            self.update_status_line(total_tasks, completed_count).await;
            
            let result = self.execute_next_task(context).await?;
            completed_count += 1;
            results.push(result);

            // Add any new tasks generated by this execution
            if let Some(next_tasks) = results.last().and_then(|r| r.next_tasks.clone()) {
                let mut queue = self.task_queue.write().await;
                for task in next_tasks {
                    queue.push_back(task);
                }
            }
        }

        // Update visibility manager with completion phase
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.set_phase(ExecutionPhase::ResultAggregation);
        }

        // 5. Synthesize final response
        let final_result = self.synthesize_response(results).await?;
        
        // Update visibility manager with completed phase
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.set_phase(ExecutionPhase::Completed);
        }
        
        Ok(final_result)
    }

    /// Analyze user request and create initial task
    async fn analyze_request(&self, request: &str) -> Result<Task> {
        let task_id = format!("task_{}", chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0));

        // Simple heuristics for task analysis
        let (task_type, priority) = if request.contains(" and ") || request.contains(" then ") || request.contains(" after ") {
            (TaskType::Complex, TaskPriority::High)
        } else if request.len() > 200 {
            (TaskType::Complex, TaskPriority::Medium)
        } else {
            (TaskType::Simple, TaskPriority::Medium)
        };

        Ok(Task {
            id: task_id,
            description: request.to_string(),
            task_type,
            priority,
            metadata: HashMap::new(),
        })
    }

    /// Decompose complex tasks into subtasks
    async fn decompose_task(&self, task: Task) -> Result<Vec<Task>> {
        match task.task_type {
            TaskType::Simple => Ok(vec![task]),
            TaskType::Complex => self.decompose_complex_task(task).await,
            TaskType::Parallel(subtasks) => Ok(subtasks),
            TaskType::Sequential(subtasks) => Ok(subtasks),
        }
    }

    /// Decompose a complex task into simpler subtasks
    async fn decompose_complex_task(&self, task: Task) -> Result<Vec<Task>> {
        let description = task.description.to_lowercase();
        let mut subtasks = Vec::new();

        // Common patterns for task decomposition
        if description.contains("read") && description.contains("write") {
            // Separate read and write operations
            subtasks.push(Task {
                id: format!("{}_read", task.id),
                description: "Read the relevant files".to_string(),
                task_type: TaskType::Simple,
                priority: TaskPriority::High,
                metadata: HashMap::new(),
            });

            subtasks.push(Task {
                id: format!("{}_write", task.id),
                description: "Write the updated content".to_string(),
                task_type: TaskType::Simple,
                priority: TaskPriority::High,
                metadata: HashMap::new(),
            });
        } else if description.contains("search") && description.contains("modify") {
            // Search then modify pattern
            subtasks.push(Task {
                id: format!("{}_search", task.id),
                description: "Search for the relevant code/files".to_string(),
                task_type: TaskType::Simple,
                priority: TaskPriority::High,
                metadata: HashMap::new(),
            });

            subtasks.push(Task {
                id: format!("{}_modify", task.id),
                description: "Modify the found code/files".to_string(),
                task_type: TaskType::Simple,
                priority: TaskPriority::High,
                metadata: HashMap::new(),
            });
        } else {
            // Default: keep as single task but mark for specialized agent
            subtasks.push(task);
        }

        Ok(subtasks)
    }

    /// Execute the next task in the queue
    async fn execute_next_task(&self, context: &ExecutionContext) -> Result<AgentResult> {
        let task = {
            let mut queue = self.task_queue.write().await;
            queue.pop_front()
                .ok_or_else(|| anyhow::anyhow!("No tasks in queue"))?
        };

        println!("{} {}", "⚡ Executing task:".cyan(), task.description.yellow());

        // Update visibility manager with task execution
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.update_task_progress(&task.id, 
                0.0, 
                "starting"
            );
        }

        // Find suitable agent for this task
        let agent = self.find_suitable_agent(&task).await?;
        let agent_name = agent.name().to_string();

        // Register agent with visibility manager
        {
            let mut visibility = self.visibility_manager.write().await;
            visibility.register_agent(agent_name.clone(), vec![task.description.clone()]);
            visibility.update_agent_status(&agent_name, 
                crate::agents::visibility::AgentStatus::Executing, 
                Some(task.description.clone())
            );
        }

        // Create execution context for this specific task
        let task_context = ExecutionContext {
            workspace_dir: context.workspace_dir.clone(),
            session_id: context.session_id.clone(),
            tool_registry: Arc::clone(&context.tool_registry),
            llm_client: Arc::clone(&context.llm_client),
            conversation_history: context.conversation_history.clone(),
        };

        // Execute task
        let start_time = std::time::Instant::now();
        let result = agent.execute(task.clone(), &task_context).await;
        let execution_time = start_time.elapsed();

        // Update visibility manager with completion
        {
            let mut visibility = self.visibility_manager.write().await;
            let status = if result.success {
                crate::agents::visibility::AgentStatus::Completed
            } else {
                crate::agents::visibility::AgentStatus::Failed("Task execution failed".to_string())
            };
            visibility.update_agent_status(&agent_name, status, None);
            visibility.update_task_progress(&task.id, 
                100.0, 
                if result.success { "completed" } else { "failed" }
            );
        }

        // Update conversation history
        {
            let mut history = self.conversation_state.write().await;
            history.push(crate::agents::agent::ChatMessage {
                role: "assistant".to_string(),
                content: format!("Agent '{}' completed task: {}", agent.name(), task.description),
                tool_calls: None,
            });
        }

        // Enhanced completion message
        println!("{}", "─".repeat(40).bright_green());
        println!("{} {} in {:.1}s", 
            "✅ Task completed by:".green().bold(), 
            agent.name().bright_white(), 
            execution_time.as_secs_f32()
        );
        
        // Show performance metrics if available
        if result.execution_time > 1000 { // More than 1 second
            println!("{} Task took longer than expected - consider optimization", "⚠️  Performance note:".yellow());
        }
        
        println!("{}", "─".repeat(40).bright_green());
        println!();

        Ok(result)
    }

    /// Update status line showing queue status
    async fn update_status_line(&self, total_tasks: usize, completed_count: usize) {
        let visibility = self.visibility_manager.read().await;
        let (pending, _active, _completed) = visibility.get_task_queue_status();
        let current_agent = visibility.get_current_agent();
        
        let status_line = format!(
            "[🤖 AGENTS] Queue: {} | Active: {} | Completed: {}/{}",
            pending,
            current_agent.unwrap_or_else(|| "none".to_string()),
            completed_count,
            total_tasks
        );
        
        if matches!(visibility.get_current_phase(), &ExecutionPhase::TaskExecution) {
            println!("{}", status_line.bright_cyan());
        }
    }

    /// Find the best agent for a given task
    async fn find_suitable_agent(&self, task: &Task) -> Result<Arc<dyn Agent>> {
        for (agent_name, config) in &self.agent_configs {
            let agent = self.agent_factory.create_agent(config)?;

            if agent.can_handle(task) {
                // Enhanced agent selection display
                let agent_model = (&config.model).as_str();
                let capabilities = config.capabilities.join(", ");
                
                println!("{}", "─".repeat(50).bright_cyan());
                println!("{} {}", "🎯 Agent Selection:".bright_cyan().bold(), agent_name.bright_white().bold());
                println!("{} {}", "📋 Task:".bright_blue(), task.description.clone().yellow());
                println!("{} {}", "🤖 Model:".bright_green(), agent_model.cyan());
                println!("{} {}", "🔧 Capabilities:".bright_purple(), capabilities.white());
                println!("{}", "─".repeat(50).bright_cyan());
                println!();
                
                return Ok(Arc::from(agent));
            }
        }

        // Fallback to a general-purpose agent
        if let Some(config) = self.agent_configs.values().next() {
            let agent = self.agent_factory.create_agent(config)?;
            println!("{} Using fallback agent for task", "🔄".yellow());
            return Ok(Arc::from(agent));
        }

        Err(anyhow::anyhow!("No suitable agent found for task"))
    }

    /// Synthesize final response from multiple agent results
    async fn synthesize_response(&self, results: Vec<AgentResult>) -> Result<AgentResult> {
        if results.is_empty() {
            return Ok(AgentResult::error(
                "No tasks were executed".to_string(),
                "synthesis".to_string(),
                "coordinator".to_string(),
            ));
        }

        if results.len() == 1 {
            return Ok(results.into_iter().next().unwrap());
        }

        // Combine multiple results
        let mut combined_content = String::new();
        let mut all_success = true;
        let mut total_time = 0u64;

        for result in &results {
            if !result.success {
                all_success = false;
            }
            total_time += result.execution_time;

            combined_content.push_str(&format!(
                "### Result from {}\n\n{}\n\n",
                result.agent_name,
                result.content
            ));
        }

        let final_result = AgentResult {
            success: all_success,
            content: combined_content.trim().to_string(),
            task_id: "synthesis".to_string(),
            agent_name: "coordinator".to_string(),
            execution_time: total_time,
            metadata: HashMap::new(),
            next_tasks: None,
        };

        println!("{} Synthesized response from {} agents", "🎨".blue(), results.len());

        Ok(final_result)
    }

    /// Get current task queue status
    pub async fn get_queue_status(&self) -> (usize, usize) {
        let queue_size = self.task_queue.read().await.len();
        let active_agents = self.active_agents.read().await.len();
        (queue_size, active_agents)
    }
}